name: 'GoDiffy Visual Regression'
description: 'Upload visual regression test screenshots to GoDiffy and generate comparison reports'
author: 'GoDiffy'
branding:
  icon: 'camera'
  color: 'blue'

inputs:
  api-key:
    description: 'GoDiffy API key for authentication'
    required: true
  site-id:
    description: 'GoDiffy Site ID'
    required: true
  images-path:
    description: 'Path to directory containing screenshots (not required if only running comparison or using capture-screenshots)'
    required: false
  capture-screenshots:
    description: 'Whether to capture screenshots from URLs defined in godiffy.json'
    required: false
    default: 'false'
  config-path:
    description: 'Path to godiffy.json configuration file'
    required: false
    default: './godiffy.json'
  base-url:
    description: 'GoDiffy API base URL (for internal use)'
    required: false
    default: 'https://godiffy-backend.up.railway.app'
  baseline-branch:
    description: 'Branch to use as baseline'
    required: false
    default: 'master'
  baseline-commit:
    description: 'Commit SHA or "latest"'
    required: false
    default: 'latest'
  create-report:
    description: 'Whether to run comparisons and save as report'
    required: false
    default: 'false'
  algorithm:
    description: 'Comparison algorithm (pixelmatch or ssim)'
    required: false
    default: 'pixelmatch'
  threshold:
    description: 'Similarity threshold (0.0-1.0, where 1.0 = identical)'
    required: false
    default: '0.9'
  post-pr-comment:
    description: 'Whether to post PR comment with results (requires create-report: true)'
    required: false
    default: 'false'
  github-token:
    description: 'GitHub token for posting PR comments (use secrets.GITHUB_TOKEN)'
    required: false

outputs:
  total-comparisons:
    description: 'Total number of comparisons performed'
  passed-comparisons:
    description: 'Number of comparisons that passed threshold'
  failed-comparisons:
    description: 'Number of comparisons that failed threshold'
  average-similarity:
    description: 'Average similarity percentage (0-100) across all comparisons'
  threshold-met:
    description: 'Whether the average similarity met the configured threshold (true/false)'
  report-id:
    description: 'ID of saved report (if saveReport was true)'
  report-url:
    description: 'URL to view report in GoDiffy dashboard (if generated)'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}
        npm install --production
        if [ "${{ inputs.capture-screenshots }}" = "true" ]; then
          npx playwright install chromium --with-deps
        fi
    
    - name: Run action
      shell: bash
      env:
        INPUT_API-KEY: ${{ inputs.api-key }}
        INPUT_SITE-ID: ${{ inputs.site-id }}
        INPUT_IMAGES-PATH: ${{ inputs.images-path }}
        INPUT_CAPTURE-SCREENSHOTS: ${{ inputs.capture-screenshots }}
        INPUT_CONFIG-PATH: ${{ inputs.config-path }}
        INPUT_BASE-URL: ${{ inputs.base-url }}
        INPUT_BASELINE-BRANCH: ${{ inputs.baseline-branch }}
        INPUT_BASELINE-COMMIT: ${{ inputs.baseline-commit }}
        INPUT_CREATE-REPORT: ${{ inputs.create-report }}
        INPUT_ALGORITHM: ${{ inputs.algorithm }}
        INPUT_THRESHOLD: ${{ inputs.threshold }}
      run: node ${{ github.action_path }}/index.js
    
    - name: Post PR comment
      if: inputs.post-pr-comment == 'true' && inputs.create-report == 'true' && always()
      uses: actions/github-script@v7
      env:
        GODIFFY_API_KEY: ${{ inputs.api-key }}
        GODIFFY_BASE_URL: ${{ inputs.base-url }}
        SITE_ID: ${{ inputs.site-id }}
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const baseUrl = process.env.GODIFFY_BASE_URL;
          const apiKey = process.env.GODIFFY_API_KEY;
          const siteId = process.env.SITE_ID;
          const branch = context.ref.replace('refs/heads/', '');
          const commit = context.sha;
          
          // Find PR number
          let prNumber = context.issue.number;
          if (!prNumber && context.eventName === 'push') {
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: `${context.repo.owner}:${branch}`
            });
            if (prs.data.length > 0) {
              prNumber = prs.data[0].number;
            }
          }
          
          if (!prNumber) {
            console.log('No PR found, skipping comment');
            return;
          }
          
          // Fetch latest report
          const reportsUrl = `${baseUrl}/api/v2/sites/${siteId}/reports?limit=10`;
          const reportsRes = await fetch(reportsUrl, {
            headers: { 'Authorization': `Bearer ${apiKey}` }
          });
          
          if (!reportsRes.ok) {
            console.log('Failed to fetch reports:', reportsRes.status);
            return;
          }
          
          const data = await reportsRes.json();
          const reports = data.reports || [];
          const report = reports.find(r => r.candidateCommit === commit);
          
          if (!report) {
            console.log('No report found for commit:', commit);
            return;
          }
          
          const avgSim = (report.averageSimilarity * 100).toFixed(2);
          const threshold = 95;
          const thresholdMet = report.averageSimilarity >= (threshold / 100);
          const passed = report.passedComparisons || 0;
          const total = report.totalComparisons || 0;
          const failed = total - passed;
          
          const status = thresholdMet ? '✅ PASSED' : '❌ FAILED';
          const icon = thresholdMet ? '✅' : '❌';
          const reportUrl = `${baseUrl}/sites/${siteId}/reports/${report.id}`;
          
          const body = `## ${icon} Visual Regression Report - ${status}
          
          **Results:** ${passed}/${total} comparisons passed
          **Average Similarity:** ${avgSim}%
          **Threshold:** ${threshold}%
          
          ${!thresholdMet ? '⚠️ **Visual changes detected that exceed the acceptable threshold**' : '✅ All visual changes are within acceptable limits'}
          ${failed > 0 ? `\n⚠️ ${failed} comparison(s) below individual threshold` : ''}
          
          **🔗 [View Full Report](${reportUrl})**
          
          ---
          *Generated by GoDiffy GitHub Action*`;
          
          await github.rest.issues.createComment({
            issue_number: prNumber,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          });
          
          if (!thresholdMet) {
            core.setFailed(`Visual regression check failed: ${avgSim}% similarity is below ${threshold}% threshold`);
          }